pipeline {
    agent any

    environment {
        APP_DIR          = 'my-java-app'
        DOCKER_IMAGE     = 'ahmad09x/java-app'
        IMAGE_TAG        = "${BUILD_NUMBER}"
        IMAGE_LATEST     = "${DOCKER_IMAGE}:latest"
        IMAGE_VERSION    = "${DOCKER_IMAGE}:${IMAGE_TAG}"

        SONARQUBE_ENV    = 'sonarqube-server'
        HELM_RELEASE     = 'java-app'
        HELM_NAMESPACE   = 'default'
        HELM_CHART_PATH  = './helm/java-app'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Test') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        mvn clean test package
                    '''
                }
            }
        }

        stage('SonarQube Scan') {
            steps {
                dir("${APP_DIR}") {
                    withSonarQubeEnv('sonarqube-server') {
                        sh '''
                            mvn sonar:sonar \
                              -Dsonar.projectKey=java-app \
                              -Dsonar.projectName=java-app
                        '''
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${APP_DIR}") {
                    sh '''
                        docker build -t ${IMAGE_VERSION} .
                        docker tag ${IMAGE_VERSION} ${IMAGE_LATEST}
                    '''
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKERHUB_USERNAME',
                    passwordVariable: 'DOCKERHUB_PASSWORD'
                )]) {
                    sh '''
                        echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
                        docker push ${IMAGE_VERSION}
                        docker push ${IMAGE_LATEST}
                    '''
                }
            }
        }

        stage('Trigger GitLab Deploy') {
    steps {
        withCredentials([string(credentialsId: 'gitlab-trigger-token', variable: 'GITLAB_TRIGGER_TOKEN')]) {
            sh '''
                curl --fail --request POST \
                  --form token=$GITLAB_TRIGGER_TOKEN \
                  --form ref=main \
                  --form "variables[IMAGE_TAG]=${IMAGE_TAG}" \
                  --form "variables[DOCKER_IMAGE]=${DOCKER_IMAGE}" \
                  https://gitlab.com/api/v4/projects/80914366/trigger/pipeline
            '''
        }
    }
}

       }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
